'use client';
import { useRouter } from 'next/navigation';
import Shell from '@/components/Shell';

type GameCardProps = { title: string; eyebrow: string; description: string; icon: string; tone: 'gold' | 'sky'; available?: boolean; onClick?: () => void };
function GameCard({ title, eyebrow, description, icon, tone, available, onClick }: GameCardProps) {
  const palette = tone === 'gold' ? 'border-gold/40 bg-gradient-to-br from-gold/[.17] to-[#101a35]/80 hover:border-gold' : 'border-sky/25 bg-gradient-to-br from-sky/[.12] to-[#101a35]/80 hover:border-sky/70';
  return <button disabled={!available} onClick={onClick} className={`design-card group relative overflow-hidden p-5 text-left transition duration-300 ${palette} ${available ? 'hover:-translate-y-1' : 'cursor-default opacity-65'}`}><div className="absolute -right-10 -top-12 h-40 w-40 rounded-full bg-white/[.05] blur-3xl transition group-hover:scale-150" /><div className="relative flex items-start justify-between"><span className="grid h-12 w-12 place-items-center rounded-2xl bg-black/25 text-2xl">{icon}</span><span className={`rounded-full border px-3 py-1 text-[10px] font-bold uppercase tracking-[.14em] ${available ? 'border-sky/30 text-sky' : 'border-white/10 text-slate-400'}`}>{available ? 'Тоглох' : 'Удахгүй'}</span></div><p className="relative mt-6 text-[10px] font-bold uppercase tracking-[.22em] text-slate-400">{eyebrow}</p><h2 className="relative mt-2 font-display text-2xl text-slate-100">{title}</h2><p className="relative mt-2 max-w-sm text-sm leading-6 text-slate-300">{description}</p>{available && <span className="relative mt-5 inline-flex text-xs font-bold text-gold">Lobby үүсгэх →</span>}</button>;
}
export default function Home() {
  const router = useRouter();
  return <Shell><section className="scene-page scene-backdrop soft-rise -mx-5 rounded-[2rem] px-5 py-7 sm:-mx-8 sm:px-8 sm:py-9"><div className="game-topbar relative z-10 mb-10 flex flex-wrap items-center justify-between gap-3 rounded-2xl px-4 py-3"><div><p className="label">Нууц ажиллагааны төв</p><p className="mt-1 font-display text-lg text-slate-100">ШПИ <span className="text-gold">GAME LOUNGE</span></p></div><div className="flex items-center gap-2"><button onClick={() => router.push('/profile')} className="game-pill rounded-xl px-4 py-2 text-xs font-bold text-slate-200">♙ Profile</button><span className="game-pill rounded-xl px-4 py-2 text-xs text-sky">● Online</span></div></div><div className="relative z-10 grid gap-10 lg:grid-cols-[.85fr_1.15fr] lg:items-center"><div className="max-w-xl"><div className="mb-5 flex items-center gap-2 text-xs font-bold uppercase tracking-[.24em] text-sky"><span className="h-px w-10 bg-sky/60" /> Тоглоомын төв</div><h1 className="gold-glow font-display text-6xl leading-[.95] tracking-[-.07em] text-slate-100 sm:text-8xl">Багтайгаа<br /><span className="text-gold">тогло.</span></h1><p className="mt-6 max-w-md text-base leading-7 text-slate-300">Дуугаар ярилцаж, сэжиглэж, нууц дүрүүдийг ол. Өөрийн avatar, малгайтайгаар ширээнд суу.</p><div className="mt-8 flex flex-wrap gap-3 text-xs font-bold text-slate-400"><span className="game-pill rounded-full px-4 py-2">4–8 тоглогч</span><span className="game-pill rounded-full px-4 py-2">Live voice</span><span className="game-pill rounded-full px-4 py-2">Монгол хэл</span></div></div><div className="relative grid gap-3"><div className="mb-1 flex items-end justify-between px-1"><div><p className="label">Сонгох тоглоом</p><h2 className="mt-2 font-display text-xl text-slate-100">Оройн тоглоомын цэс</h2></div><span className="text-xs text-slate-500">01 / 02</span></div><GameCard title="Шпи" eyebrow="Social deduction · 4–8 хүн" description="Нэг нь шпи. Бусад нь байршлыг мэднэ. Яриа, асуултаар үнэнийг ол." icon="🕵️" tone="gold" available onClick={() => router.push('/spyfall')} /><GameCard title="Codenames" eyebrow="Team word game · 4+ хүн" description="Багийнхандаа оновчтой clue өгч, нууц үгсийг зөв таалга." icon="🃏" tone="sky" /></div></div><div className="floating-panel relative z-10 mt-10 flex flex-wrap items-center justify-between gap-4 rounded-2xl px-5 py-4"><div><p className="text-sm font-bold text-slate-100">Ширээндээ найзуудаа урь</p><p className="mt-1 text-xs text-slate-400">Lobby үүсгээд кодоо хуваалцаарай.</p></div><button onClick={() => router.push('/spyfall')} className="btn btn-gold !rounded-xl !px-5 !py-2.5 text-sm">Ширээ нээх →</button></div></section></Shell>;
}
